---
- hosts: all
  tasks:
    - name: install apache
      sudo: yes
      apt: name=apache2 state=present update_cache=yes

    - name: install php build requirements
      sudo: yes
      apt: name={{item}} state=present update_cache=yes
      with_items:
       - autoconf
       - libxml2-dev
       - automake
       - libtool
       - re2c
       - flex
       - bison

    - name: install old php
      script: install_php.sh

    - name: install apache php module
      sudo: yes
      apt: name=libapache2-mod-php5 state=present
      notify: start apache

  handlers:
    - name: start apache
      sudo: yes
      service: name=apache2 state=running enabled=yes
